In [2]:
import pandas as pd

# Reading a .csv from a URL with Pandas

##### Target website: https://www.football-data.co.uk/data.php

In [7]:
#reading 1 csv file from the website 
df_premier25 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/E0.csv")

In [8]:
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,E0,14/03/2026,20:00,West Ham,Man City,1,1,D,1,1,...,2.05,1.80,NaN,NaN,2.05,1.83,1.99,1.79,2.15,1.85
296,E0,15/03/2026,14:00,Crystal Palace,Leeds,0,0,D,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.89,1.88,2.01,1.97
297,E0,15/03/2026,14:00,Man United,Aston Villa,3,1,H,0,0,...,1.90,1.95,NaN,NaN,1.93,1.96,1.88,1.90,1.96,2.02
298,E0,15/03/2026,14:00,Nott'm Forest,Fulham,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.85,2.04,1.93
299,E0,15/03/2026,16:30,Liverpool,Tottenham,1,1,D,1,0,...,1.80,2.00,NaN,NaN,1.85,2.05,1.77,1.96,1.88,2.11

In [10]:
#rename columns
df_premier25.rename(columns={"FTHG":"home_goals",
                             "FTAG":"away_goals"}, inplace=True)

In [11]:
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,E0,14/03/2026,20:00,West Ham,Man City,1,1,D,1,1,...,2.05,1.80,NaN,NaN,2.05,1.83,1.99,1.79,2.15,1.85
296,E0,15/03/2026,14:00,Crystal Palace,Leeds,0,0,D,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.89,1.88,2.01,1.97
297,E0,15/03/2026,14:00,Man United,Aston Villa,3,1,H,0,0,...,1.90,1.95,NaN,NaN,1.93,1.96,1.88,1.90,1.96,2.02
298,E0,15/03/2026,14:00,Nott'm Forest,Fulham,0,0,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.91,1.92,1.85,2.04,1.93
299,E0,15/03/2026,16:30,Liverpool,Tottenham,1,1,D,1,0,...,1.80,2.00,NaN,NaN,1.85,2.05,1.77,1.96,1.88,2.11

## Reading .csv from Multiple URLs with Pandas

##### https://www.football-data.co.uk/mmz4281/2526/E0.csv

##### link: root + season + league

In [15]:
# a root variable - all links has this root in common:
root = "https://www.football-data.co.uk/mmz4281/"

In [20]:
#list of leagues
leagues = ["E0","E1","E2","E3","EC"]
frames = []

#LOOPING THORUGH LEAGUES, READING MULTIPLE CSV AND APPEND IT INTO A LIST
for league in leagues:
    df = pd.read_csv(root + "2526" + "/" + league + ".csv")
    frames.append(df)

In [22]:
#length of frames
len(frames)

5

In [25]:
#sbow 1st, 2nd and 3rd elemtn
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,EC,14/03/2026,15:00,Tamworth,Carlisle,2,1,H,0,0,...,1.95,1.85,NaN,NaN,1.95,1.85,1.89,1.81,2.02,1.93
442,EC,14/03/2026,15:00,Truro,Hartlepool,0,1,A,0,0,...,1.85,1.95,NaN,NaN,1.85,1.95,1.81,1.88,1.91,2.03
443,EC,14/03/2026,17:30,Eastleigh,Rochdale,1,3,A,0,1,...,1.93,1.88,NaN,NaN,1.93,1.88,1.89,1.81,2.00,1.91
444,EC,14/03/2026,17:30,Morecambe,Braintree Town,1,1,D,0,0,...,1.83,1.98,NaN,NaN,1.85,1.98,1.79,1.91,1.86,2.14
445,EC,14/03/2026,17:30,Scunthorpe,Altrincham,2,1,H,0,1,...,1.80,2.00,NaN,NaN,1.80,2.00,1.76,1.94,1.88,2.07

## Multiple Seasons

In [28]:
#list of leagues
leagues = ["E0","E1","E2"]
frames = []

#LOOPING THORUGH LEAGUES, READING MULTIPLE CSV AND APPEND IT INTO A LIST
for league in leagues:
    for season in range(19, 25):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + league + ".csv", encoding="unicode_escape")
        df.insert(1, "season", season)
        frames.append(df)

In [29]:
#total frames : 6 seasons x 3 leagues
len(frames)

18

In [31]:
#show 1st and last elemnt (new season column was creates)
frames[17]

,ï»¿Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,24,09/08/2024,20:00,Barnsley,Mansfield,1,2,A,1,...,2.03,1.83,2.02,1.87,2.05,2.00,1.95,1.85,2.06,1.93
1,E2,24,10/08/2024,17:30,Birmingham,Reading,1,1,D,0,...,1.80,2.05,1.81,2.10,1.83,2.10,1.80,2.01,1.82,2.16
2,E2,24,10/08/2024,17:30,Bristol Rvs,Northampton,1,0,H,0,...,1.98,1.88,1.98,1.91,1.98,1.92,1.93,1.86,2.02,1.97
3,E2,24,10/08/2024,17:30,Burton,Lincoln,2,3,A,2,...,1.80,2.05,1.82,2.08,1.88,2.09,1.80,2.01,1.88,2.11
4,E2,24,10/08/2024,17:30,Crawley Town,Blackpool,2,1,H,2,...,1.83,2.03,1.85,2.04,1.86,2.05,1.82,1.99,1.89,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,24,03/05/2025,15:00,Northampton,Wigan,1,1,D,1,...,2.05,1.80,2.09,1.78,2.11,1.80,2.03,1.78,2.13,1.84
548,E2,24,03/05/2025,15:00,Reading,Barnsley,2,4,A,0,...,1.85,2.00,1.79,2.07,1.85,2.12,1.79,2.03,1.87,2.11
549,E2,24,03/05/2025,15:00,Rotherham,Peterboro,2,1,H,1,...,1.93,1.93,1.93,1.92,2.00,1.95,1.91,1.89,1.98,2.00
550,E2,24,03/05/2025,15:00,Shrewsbury,Crawley Town,1,2,A,0,...,2.03,1.83,2.05,1.81,2.10,1.83,2.03,1.79,2.11,1.87
551,E2,24,03/05/2025,15:00,Wycombe,Stockport,1,3,A,1,...,1.85,2.00,1.87,1.99,1.87,2.15,1.80,2.04,1.88,2.11

## Organize All the data in a Dictionary

In [37]:
dict_countries = {
    "Spanish La Liga":"SP1", "Spanish Segunda Division":"SP2",
    "German Bundesliga":"D1",
    "English Premmier League":"E0", "English League 1":"E2", "English League 2":"E3"
}

In [35]:
dict_countries["Spanish La liga"]

'SP1'

In [42]:
dict_historical_data = {}


#list of leagues
#leagues = ["E0","E1","E2"]

#LOOPING THORUGH LEAGUES, READING MULTIPLE CSV AND APPEND IT INTO A LIST
for league in dict_countries:
    frames = []
    for season in range(19, 25):
        df = pd.read_csv(root + str(season) + str(season+1) + "/" + dict_countries[league] + ".csv", encoding="unicode_escape")
        df.insert(1, "season", season)
        frames.append(df)   
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [47]:
#svi keyevi tj lige
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premmier League', 'English League 1', 'English League 2'])

In [49]:
#show datagrame inside dict_historical_data
dict_historical_data["Spanish La Liga"]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,SP1,19,16/08/2019,20:00,Ath Bilbao,Barcelona,1,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,19,17/08/2019,16:00,Celta,Real Madrid,1,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,19,17/08/2019,18:00,Valencia,Sociedad,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,19,17/08/2019,19:00,Mallorca,Eibar,2,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,19,17/08/2019,20:00,Leganes,Osasuna,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,24,24/05/2025,20:00,Getafe,Celta,1,2,A,1,...,4.85,3.88,1.77,5.30,3.9,1.79,2.08,1.89,1.95,2.03
376,NaN,24,24/05/2025,20:00,Vallecano,Mallorca,0,0,D,0,...,1.53,4.19,7.29,1.50,4.6,8.20,2.10,1.87,1.85,2.14
377,NaN,24,25/05/2025,13:00,Girona,Ath Madrid,0,4,A,0,...,3.48,3.57,2.16,3.50,3.7,2.24,1.60,2.64,2.04,1.94
378,NaN,24,25/05/2025,15:15,Villarreal,Sevilla,4,2,H,3,...,1.75,4.42,4.30,1.80,4.3,4.60,1.60,2.62,2.03,1.95
379,NaN,24,25/05/2025,20:00,Ath Bilbao,Barcelona,0,3,A,0,...,3.49,4.00,2.03,3.35,4.0,2.18,1.47,3.05,2.07,1.91